package io.landolfi.integration;

import io.landolfi.customer.AddressDto;
import io.landolfi.customer.CustomerDto;
import io.landolfi.customer.CustomerResource;
import io.quarkus.test.common.http.TestHTTPEndpoint;
import io.quarkus.test.common.http.TestHTTPResource;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.MediaType;
import java.net.URI;
import java.util.UUID;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

@QuarkusTest
@TestHTTPEndpoint(CustomerResource.class)
class CustomerResourceTest {
    @TestHTTPEndpoint(CustomerResource.class)
    @TestHTTPResource
    URI customersUri;

    @Test
    void shouldCreateTheGivenCustomerSuccessfullyIgnoringTheClientProvidedCustomerUuid_WhenPostingToTheEndpoint() {
        AddressDto givenAddress = new AddressDto("Via fasulla 10", "Padova", "Padova", "Veneto");
        // Assuming that the client is trying to provide a UUID even though he is not allowed to do so,
        // since the UUID must be generated by the server itself
        CustomerDto givenCustomer = new CustomerDto(UUID.randomUUID(), "Nicola", "Landolfi", "XFFTPK41D24B969W",
                givenAddress);

        given()
            .contentType(MediaType.APPLICATION_JSON)
            .body(givenCustomer)
        .when()
            .post()
        .then()
            .statusCode(201)
            .header(HttpHeaders.LOCATION,
                    customersUri.resolve(customersUri.getPath() + "/c8a255af-208d-4a98-bbff-8244a7a28609").toString())
            .body("uuid", equalTo("c8a255af-208d-4a98-bbff-8244a7a28609"))
            .body("name", equalTo("Nicola"))
            .body("surname", equalTo("Landolfi"))
            .body("fiscal_code", equalTo("XFFTPK41D24B969W"))
            .body("address.street", equalTo("Via fasulla 10"))
            .body("address.city", equalTo("Padova"))
            .body("address.province", equalTo("Padova"))
            .body("address.region", equalTo("Veneto"));
    }

    @Test
    void shouldCreateTheGivenCustomerSuccessfullyWithServerSideGeneratedCustomerUuid_WhenPostingToTheEndpoint() {
        AddressDto givenAddress = new AddressDto("Via fasulla 10", "Padova", "Padova", "Veneto");
        CustomerDto givenCustomer = new CustomerDto("Nicola", "Landolfi", "XFFTPK41D24B969W",
                givenAddress);

        given()
            .contentType(MediaType.APPLICATION_JSON)
            .body(givenCustomer)
        .when()
            .post()
        .then()
            .statusCode(201)
            .header(HttpHeaders.LOCATION,
                    customersUri.resolve(customersUri.getPath() + "/c8a255af-208d-4a98-bbff-8244a7a28609").toString())
            .body("uuid", equalTo("c8a255af-208d-4a98-bbff-8244a7a28609"))
            .body("name", equalTo("Nicola"))
            .body("surname", equalTo("Landolfi"))
            .body("fiscal_code", equalTo("XFFTPK41D24B969W"))
            .body("address.street", equalTo("Via fasulla 10"))
            .body("address.city", equalTo("Padova"))
            .body("address.province", equalTo("Padova"))
            .body("address.region", equalTo("Veneto"));
    }
}
